apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: platform-ref-azure
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/platform-ref-azure
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This reference platform Configuration for Kubernetes and Data Services
      is a starting point to build, run, and operate your own internal cloud
      platform and offer a self-service console and API to your internal teams.

    meta.crossplane.io/readme: |
      This reference platform `Configuration` for Kubernetes and Data Services
      is a starting point to build, run, and operate your own internal cloud
      platform and offer a self-service console and API to your internal teams.
      It provides platform APIs to provision fully configured AKS clusters,
      with secure networking, and stateful cloud services designed to
      securely connect to the nodes in each AKS cluster -- all composed using
      cloud service primitives from the [Upbound Official Azure
      Provider](https://marketplace.upbound.io/providers/upbound/provider-azure). App
      deployments can securely connect to the infrastructure they need using
      secrets distributed directly to the app namespace.

      [Quickstart
      Guide](https://github.com/upbound/platform-ref-azure/#quickstart)

      [Customize for your
      Organization](https://github.com/upbound/platform-ref-azure/#customize-for-your-organization)

      To learn more checkout the [GitHub
      repo](https://github.com/upbound/platform-ref-azure/) that you can copy and
      customize to meet the exact needs of your organization!
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-azure-network
      # renovate: datasource=github-releases depName=upbound/configuration-azure-network
      version: "v0.8.0"
    - configuration: xpkg.upbound.io/upbound/configuration-azure-aks
      # renovate: datasource=github-releases depName=upbound/configuration-azure-aks
      version: "v0.7.0"
    - configuration: xpkg.upbound.io/upbound/configuration-azure-database
      # renovate: datasource=github-releases depName=upbound/configuration-azure-database
      version: "v0.12.0"
    - configuration: xpkg.upbound.io/upbound/configuration-app
      # renovate: datasource=github-releases depName=upbound/configuration-app
      version: "v0.5.0"
    - configuration: xpkg.upbound.io/upbound/configuration-observability-oss
      # renovate: datasource=github-releases depName=upbound/configuration-observability-oss
      version: "v0.5.0"
    - configuration: xpkg.upbound.io/upbound/configuration-gitops-flux
      # renovate: datasource=github-releases depName=upbound/configuration-gitops-flux
      version: "v0.6.0"
