kubectl delete -f ./cluster/definition.yaml
kubectl delete -f ./cluster/composition.yaml
kubectl delete -f ./cluster/aks/definition.yaml
kubectl delete -f ./cluster/aks/composition.yaml
kubectl delete -f ./cluster/network/definition.yaml
kubectl delete -f ./cluster/network/composition.yaml
kubectl delete -f ./cluster/services/definition.yaml
kubectl delete -f ./cluster/services/composition.yaml
kubectl delete -f ./database/postgres/definition.yaml
kubectl delete -f ./database/postgres/composition.yaml
kubectl create -f ./cluster/definition.yaml
kubectl create -f ./cluster/composition.yaml
kubectl create -f ./cluster/aks/definition.yaml
kubectl create -f ./cluster/aks/composition.yaml
kubectl create -f ./cluster/network/definition.yaml
kubectl create -f ./cluster/network/composition.yaml
kubectl create -f ./cluster/services/definition.yaml
kubectl create -f ./cluster/services/composition.yaml
kubectl create -f ./database/postgres/definition.yaml
kubectl create -f ./database/postgres/composition.yaml