apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xaks.azure.platformref.upbound.io
  labels:
    provider: azure
spec:
  compositeTypeRef:
    apiVersion: azure.platformref.upbound.io/v1alpha1
    kind: XAKS
  resources:
    - name: kubernetes-cluster
      base:
        apiVersion: containerservice.azure.upbound.io/v1beta1
        kind: KubernetesCluster
        spec:
          forProvider:
            location: West US 2
            kubernetesVersion: "1.24.9"
            defaultNodePool:
              - name: default
                nodeCount: 1 #patched
                vmSize: Standard_B2s #patched
            identity:
              - type: "SystemAssigned"
            apiServerAccessProfile:
              - authorizedIpRanges:
                  - 0.0.0.0/0
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-aks"
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.upbound.io/network-id]
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.vnetSubnetIdSelector.matchLabels[azure.platformref.upbound.io/network-id]
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.dnsPrefix
        - fromFieldPath: spec.parameters.nodes.size
          toFieldPath: spec.forProvider.defaultNodePool[0].vmSize
          transforms:
            - type: map
              map:
                small: Standard_B2s
                medium: Standard_B4ms
                large: Standard_B8ms
        - fromFieldPath: spec.parameters.nodes.count
          toFieldPath: spec.forProvider.defaultNodePool[0].nodeCount
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: spec.writeConnectionSecretToRef.name
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-aks"
        - fromFieldPath: spec.parameters.authorizedIpRange
          toFieldPath: spec.forProvider.apiServerAccessProfile[0].authorizedIpRanges[0]
      connectionDetails:
        - fromConnectionSecretKey: kubeconfig
    - name: provider-config-helm
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              key: kubeconfig
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.credentials.secretRef.namespace
        # This ProviderConfig uses the above AKS cluster's connection secret as
        # its credentials secret.
        - fromFieldPath: spec.writeConnectionSecretToRef.name
          toFieldPath: spec.credentials.secretRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-aks"
      readinessChecks:
        - type: None
