apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xservices.azure.platformref.upbound.io
  labels:
    type: default
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: azure.platformref.upbound.io/v1alpha1
    kind: XServices
  patchSets:
    - name: Common
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - type: FromCompositeFieldPath
          fromFieldPath: spec.providerConfigRef.name
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
  resources:
    - name: releasePrometheus
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          rollbackLimit: 3
          forProvider:
            namespace: operators
            chart:
              name: kube-prometheus-stack
              repository: https://prometheus-community.github.io/helm-charts
              version: "41.4.1"
            values: {}
      patches:
        - type: PatchSet
          patchSetName: Common
        - fromFieldPath: spec.operators.prometheus.version
          toFieldPath: spec.forProvider.chart.version
