apiVersion: platform.upbound.io/v1alpha1
kind: App
metadata:
  name: platform-ref-azure-cluster-ghost
  namespace: default
  labels:
    platform.upbound.io/deletion-ordering: enabled
spec:
  compositeDeletePolicy: Foreground
  parameters:
    providerConfigName: platform-ref-azure-cluster
    passwordSecretRef:
      namespace: default
      name: platform-ref-azure-cluster-db-conn-mysql
  writeConnectionSecretToRef:
    name: platform-ref-azure-cluster-app-conn
