apiVersion: platform.upbound.io/v1alpha1
kind: App
metadata:
  name: platform-ref-azure-cluster-ghost
  namespace: default
  labels:
    platform.upbound.io/deletion-ordering: enabled
spec:
  parameters:
    helm:
      chart:
        name: ghost
        repo: "oci://registry-1.docker.io/bitnamicharts"
        version: 25.0.4
      wait: false
    providerConfigName: platform-ref-azure-cluster
    passwordSecretRef:
      namespace: default
      name: platform-ref-azure-cluster-db-conn-mysql
