apiVersion: azure.platformref.upbound.io/v1alpha1
kind: App
metadata:
  name: platform-ref-azure-ghost
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    providerConfigName: platform-ref-azure
    passwordSecretRef:
      namespace: default
      name: platform-ref-azure-db-conn-mariadb
  writeConnectionSecretToRef:
    name: platform-ref-azure-app-conn
