apiVersion: azure.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: azure
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: azure-creds
      key: key
