apiVersion: azure.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-azure-cluster
  namespace: default
spec:
  parameters:
    id: platform-ref-azure-cluster
    region: westus
    version: "1.34"
    nodes:
      count: 1
      instanceType: Standard_B2s
    gitops:
      git:
        url: https://github.com/upbound/platform-ref-azure/
        ref:
          name: refs/heads/main
        interval: 5m0s
        timeout: 60s
        path: /
