apiVersion: azure.platform.upbound.io/v1alpha1
kind: SQLInstance
metadata:
  name: platform-ref-azure-db-mariadb
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      dbengine: mariadb
  parameters:
    region: westus
    storageGB: 5 #Minimum value is 5
    version: "10.3"
    passwordSecretRef:
      namespace: default
      name: mariadbsecret
      key: password
    networkRef:
      id: platform-ref-azure #This field must match the cluster XR spec.id
  writeConnectionSecretToRef:
    name: platform-ref-azure-db-conn-mariadb #Must be unique for each instance
---
apiVersion: v1
data:
  password: dXBiMHVuZHIwY2s1ITMxMzM3
kind: Secret
metadata:
  name: mariadbsecret
  namespace: default
type: Opaque
