apiVersion: azure.platform.upbound.io/v1alpha1
kind: SQLInstance
metadata:
  name: platform-ref-azure-cluster-db-mysql
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      dbengine: mysql
  parameters:
    region: westus
    storageGB: 20 #Minimum value is 20 for MySQL
    version: "8.0"
    passwordSecretRef:
      namespace: default
      name: mysqlsecret
      key: password
    networkRef:
      id: platform-ref-azure-cluster #This field must match the cluster XR spec.parameters.id
  writeConnectionSecretToRef:
    name: platform-ref-azure-cluster-db-conn-mysql #Must be unique for each instance
---
apiVersion: v1
data:
  password: dXBiMHVuZHIwY2s1ITMxMzM3
kind: Secret
metadata:
  name: mysqlsecret
  namespace: default
type: Opaque
