name: yamllint
on: [pull_request]
jobs:
  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: yamllint
        uses: reviewdog/action-yamllint@e02a49fdf53f51ddd8dfa89b09aa975043aeba38 # v1.23.0
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          yamllint_flags: 'apis/'
          fail_on_error: true
